### ISSUE TITLE
Can it run in win7?

### ISSUE THREAD

**Issue by jackusay** [AlienCowEatCake/ImageViewer#19]
I run this file:
[ImageViewer_qt6.7_msvc2022_x64.zip](https://github.com/AlienCowEatCake/ImageViewer/releases/download/v1.6.2/ImageViewer_qt6.7_msvc2022_x64.zip)

get:

![2024-09-01 15_16_53-ImageViewer_qt6 7_msvc2022_x64](https://github.com/user-attachments/assets/50bf63fd-034e-4c78-96a1-2cede790f221)

text version:
```
ImageViewer.exe - Entry Point Not Found

The procedure entry point ProcessPrng could not be located in the dynamic link library bcryptprimitives.dll.
```

**Comment by AlienCowEatCake** [comment]
Binary builds are incompatible with Windows 7 since [1.6.0 release](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.6.0). They are built with Qt 6.x, but Qt 5.15 is latest version with Windows 7 support.

You can use binary builds from [1.5.6 release](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.5.6) or build latest version from source with Qt 5.15 or earlier.

I will probably make at least one more build for older systems in future. If you are interested in such builds, please let me know
