### ISSUE TITLE
How to provide translations?

### ISSUE THREAD

**Issue by jackusay** [AlienCowEatCake/ImageViewer#20]
It seems the translation is just some .qm files. 

How do I generate a .qm file?

**Comment by jackusay** [comment]
pull https://github.com/AlienCowEatCake/ImageViewer/pull/21

**Comment by AlienCowEatCake** [comment]
You can read the localization documentation here: [https://doc.qt.io/qt-6/linguist-creating-ts-files.html](https://doc.qt.io/qt-6/linguist-creating-ts-files.html). Also documentation for [lupdate](https://doc.qt.io/qt-6/linguist-lupdate.html) and [lrelease](https://doc.qt.io/qt-6/linguist-lrelease.html) may be useful for you.

Please note that currently `lupdate` cannot parse [src/ImageViewer/ImageViewer.pro](https://github.com/AlienCowEatCake/ImageViewer/blob/1687e991f652b096264b6ce23af1e58acf05dd8b/src/ImageViewer/ImageViewer.pro) subproject correctly and loses some source files. I'm using [src/ImageViewer/update_translations.sh](https://github.com/AlienCowEatCake/ImageViewer/blob/1687e991f652b096264b6ce23af1e58acf05dd8b/src/ImageViewer/update_translations.sh) script for this subproject. This script creates a temporary project to which all sources are added unconditionally. I plan to fix it soon, but so far it is.

Since you are planning to add a new language, PR #12 may be useful as example

**Comment by AlienCowEatCake** [comment]
> Please note that currently `lupdate` cannot parse [src/ImageViewer/ImageViewer.pro](https://github.com/AlienCowEatCake/ImageViewer/blob/1687e991f652b096264b6ce23af1e58acf05dd8b/src/ImageViewer/ImageViewer.pro) subproject correctly and loses some source files. I'm using [src/ImageViewer/update_translations.sh](https://github.com/AlienCowEatCake/ImageViewer/blob/1687e991f652b096264b6ce23af1e58acf05dd8b/src/ImageViewer/update_translations.sh) script for this subproject. This script creates a temporary project to which all sources are added unconditionally. I plan to fix it soon, but so far it is.

It was fixed in [7c9c034](https://github.com/AlienCowEatCake/ImageViewer/commit/7c9c034474705a7ba0c9039b290a195b7c7171f9). Regular `lupdate` call should work as expected for now. `update_translations.sh` is not needed anymore

**Comment by jackusay** [comment]
Do I need to Building the app?

Do I need to follow PR https://github.com/AlienCowEatCake/ImageViewer/pull/12 ?
He uploads a lot of file...

or

I can just upload 
src/ImageViewer/resources/translations/imageviewer_zh_TW.ts
src/QtUtils/resources/translations/qtutils_zh_TW.ts
?

**Comment by nonwill** [comment]
> Do I need to follow PR #12 ?

### Add files:
src/ImageViewer/resources/translations/imageviewer_zh_TW.ts
src/QtUtils/resources/translations/qtutils_zh_TW.ts

### Then run lrelease on them, and Add the output files:
src/ImageViewer/resources/translations/imageviewer_zh_TW.qm
src/QtUtils/resources/translations/qtutils_zh_TW.qm

### Update files (add support codes for  above files):
src/ImageViewer/ImageViewer.pro
src/QtUtils/QtUtils.pro
src/ImageViewer/resources/translations/imageviewer_translations.qrc
src/QtUtils/resources/translations/qtutils_translations.qrc
src/QtUtils/src/Utils/LocalizationManager.cpp
src/QtUtils/src/Utils/LocalizationManager.h

**Comment by AlienCowEatCake** [comment]
> Do I need to Building the app?

Yes if you want to test your translation. No if there is no need for it. Currently there is no way to test translation changes without rebuilding app

> Do I need to follow PR #12 ?
> He uploads a lot of file...

Unfortunately this is minimal changes if you want to run app with new language. All supported languages are hardcoded and all translations are compiled in binary for historical reasons

> I can just upload
> src/ImageViewer/resources/translations/imageviewer_zh_TW.ts
> src/QtUtils/resources/translations/qtutils_zh_TW.ts
> ?

Yes, it is possible. I can do all integration work myself
